### ISSUE TITLE
token is hostPath instead of emptyDir + ssh authorized_key nil error

### ISSUE THREAD

**Issue by antoinetran** [interTwin-eu/interlink-helm-chart#5]
# Short Description of the issue

1. In OIDC mode, the refresh token shared between vk and refresh-token is now in hostPath:/tmp (see https://github.com/interTwin-eu/interlink-helm-chart/blob/main/interlink/templates/virtual-kubelet.yaml#L160), instead of emptyDir as before (0.3.1-rc2). This causes me a regression because after each deployment, I need to delete the refresh token manually.
2. by default, when ssh bastion is not  enabled, the secret regarding the authorized_key is still created, but because it is empty, the `kubectl apply` gives an error because of nil value.

## Environment

- Operating System:
- Other related components versions:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes

**Comment by dciangot** [comment]
Should be solved now. Default is emptyDir and the secrets should not be created anymore when ssh bastion is disabled
